== !

[source]
--
lucas_r = {:(a, b, n)
  print(a);
  if (not(equals(0, n)), { lucas_r(b, a+b, n-1); }, {});
};

lucas = {:(n)
  lucas_r(2, 1, n-1);
};

lucas(10);
--

[.notes]
--
In the little picture I just showed you, we started on the left with a program of some sort. Now, that could have been a JavaScript program, or any other language you fancied actually, but that would make the rest of what we're going to talk about much more complicated and long-winded, and you know, you've got homes to go to and all that.

Instead, our little example program is in a language you almost certainly haven't heard of. The language is called *cell*, and it was invented by my friend Andy Balaam for a conference session he did a few years ago.
--

== !

Cell is a programming language with

[%step]
* a short implementation
* there is nothing else good about it, according to Andy

[.notes]
--
Cell is, Andy says, a programming language with a short implementation and that there is nothing else good about it. I'm not sure about that.

Cell is a very simple language, but even the simplest language gives us enough to keep things interesting.

Let's have a quick look at it.
--

== !

[source]
--
n = 3;

square = {:(x) x * x; };

n2 = square(n);
--

[.notes]
--
We can put a value into a name - n = 3;

Or we can define a function - square = ...

And we can call a function like this - n2 = square ...
--

== !

[source]
--
x = 3

4 + y

sqrt(-1)

{:(x, y) x*x + y*y;}
--

[.notes]
--
Everything in cell is an expression - 3
Cell only has four expression types

* assignment - put a value into a name

* operations

* function calls

* function definitions

:(x, y) are the function params, x*x+y*y is the body of the function. The return value is the last expression evaluated in the function.

Can't reassign names, although there is a standard function to do that.

Cell has no keywords, but it does have a small standard library.
--

== !

[source]
--
if(
  is_odd( 3 ),
  { print "Odd!"; },
  { print "Even."; }
);
--

[.notes]
--
Probably the most immediately useful of the standard functions is `if`. That's right, `if` is a function

`if` is a function, this is the condition, the function to execute if its true, and the function to execution if it isn't.
--

== !

[source]
--
x = "BrumJS";

fn = {
  x = "Hello";
  print( x );
};

fn();

print( x );
--

[.notes]
--
Scoping is normal.
--

== !

[source]
--
x = "BrumJS";

fn = {
  x = "Hello";
  print( x );
};

fn();

print( x );
--

[source]
--
Hello
World
--

[.notes]
--
Scoping is normal.
--

== !

[source]
--
outerfn = {
  x = 12;
  innerfn = {
    print(x);
  };
  innerfn;
};

thing = outerfn();
thing();
--

[.notes]
--
First class functions and closures!

And that's it! That's cell.
--

== !

[source]
--
lucas_r = {:(a, b, n)
  print(a);
  if (not(equals(0, n)), { lucas_r(b, a+b, n-1); }, {});
};

lucas = {:(n)
  lucas_r(2, 1, n-1);
};

lucas(10);
--

[.notes]
--
We can all read this now, right?

This generates the Lucas numbers, which is similar to the Fibonacci numbers, but less well known :)
--
