[background-image='images/brumjs.png']
[background-size='400px 600px']
== !

*Down to the Metal*

Jez Higgins

[NOTE.speaker]
--
Hello everyone - I'm Jez. I'm a freelance software grandad and I'm available, on a very flexible freelance basis, to try and help prevent you from falling down the old mine shaft :)

Dan was kind enough to invite me to speak here at Brum.js a couple of years ago, during which I didn't mention JavaScript once. There will, however, be some JavaScript this evening.
--

[background-image='images/ASR-33_2.jpg']
== !

[NOTE.speaker]
--
The invention of devices like this changed the way programmers communicate with their computers.

This is a Teletype Model 33, introduced in 1963. There's a lovely chunky keyboard there, and the output is printed on this roll of paper here. These were only discontinued in 1981, which is pretty remarkable.

Affordable high-end video displays came in around 1970, and by affordable I mean about $10000. The more every day VT52 launched in 1974, and that probably marked that start of the decline of the teletype.

The shadow cast by those early devices is still with us

* the /dev/tty on your Linux boxes
* Ray Tomlinson chose @ as the address separator - it was one of the symbols available on an ASR-33
* The VT52 screen size was 24 rows by 80 columns

These days of course, many of are rocking two, three, or even more screens. But despite all that screen space, of the incredible computer power of our CPUs and GPUs, we're still in the longest, deepest shadow cast by those mechanical teletypes.

We communicate with our computers through the medium of text.

When we want a computer to do something, we write - we type - a program that - hopefully - expresses what that something is. Then - all things being well - the computer does that thing.

But ...
--

[background-image='images/the-matrix-digital-rain.jpg']
== !

[white]#*How does the text we type*#

[white]#*turn into the computer*#

[white]#*actually doing things?*#

== !

[source,javascript]
--
const canvas = document.getElementById('canvas')
const ctx = canvas.getContext('2d')

const WIDTH = ctx.canvas.width
const HEIGHT = ctx.canvas.height

const REAL = { start: -2, range: 3 }
const IMAGINARY = { start: -1, range: 2 }

const colors = new Array(16).fill(0).map((_, i) => i === 0 ? '#000' : `#${((1 << 24) * Math.random() | 0).toString(16)}`)

for (let i = 0; i < WIDTH; ++i) {
  for (let j = 0; j < HEIGHT; ++j) {
    const complex = {
      x: REAL.start + (i / WIDTH) * REAL.range,
      y: IMAGINARY.start + (j / HEIGHT) * IMAGINARY.range
    }

    const [m, is] = fn(complex)
    ctx.fillStyle = colors[is ? 0 : (m % colors.length - 1) + 1]
    ctx.fillRect(i, j, 1, 1)
  }
}
--

[NOTE.speaker]
--
How does something like this?
--

== !

++++
<canvas width="800" height="600" id="myCanvas"/>
<script type="text/javascript">
const MAX_ITERATION = 80
function mandelbrot(c) {
    let z = { x: 0, y: 0 }, n = 0, p, d;
    do {
        p = {
            x: Math.pow(z.x, 2) - Math.pow(z.y, 2),
            y: 2 * z.x * z.y
        }
        z = {
            x: p.x + c.x,
            y: p.y + c.y
        }
        d = Math.sqrt(Math.pow(z.x, 2) + Math.pow(z.y, 2))
        n += 1
    } while (d <= 2 && n < MAX_ITERATION)
    return [n, d <= 2]
}

var canvas = document.getElementById('myCanvas')
var ctx = canvas.getContext('2d')

const WIDTH = ctx.canvas.width
const HEIGHT = ctx.canvas.height

const REAL = { start: -2, range: 3 }
const IMAGINARY = { start: -1, range: 2 }

const colors = new Array(16).fill(0).map((_, i) => i === 0 ? '#000' : `#${((1 << 24) * Math.random() | 0).toString(16)}`)

function draw() {
    for (let i = 0; i < WIDTH; i++) {
        for (let j = 0; j < HEIGHT; j++) {
            complex = {
                x: REAL.start + (i / WIDTH) * REAL.range,
                y: IMAGINARY.start + (j / HEIGHT) * IMAGINARY.range
            }

            const [m, isMandelbrotSet] = mandelbrot(complex)
            ctx.fillStyle = colors[isMandelbrotSet ? 0 : (m % colors.length - 1) + 1]
            ctx.fillRect(i, j, 1, 1)
        }
    }
}

draw();
</script>
++++

[NOTE.speaker]
--
How does something like this?
--

== !

[large]#SOFTWARE#

[NOTE.speaker]
--
Of course. We do it with software.
--

== !

[large]#SOFTWARE#

[medium]#SOFTWARE#

SOFTWARE

SOFTWARE

[small]#SOFTWARE#

[small]#SOFTWARE#

[small]#SOFTWARE#

[small]#SOFTWARE#

[small]#SOFTWARE#

[small]#SOFTWARE#

[small]#SOFTWARE#

[small]#SOFTWARE#

[NOTE.speaker]
--
It's software all the way down. Obviously.
--

